[package]
name = "sheetio"
version = "0.3.7"
edition = "2021"
authors = ["Kristian dF Kollsgård <kkollsg@gmail.com>"]
description = "A fast Rust-powered tool for extracting data from Excel forms into JSON."
readme = "README.md"
repository = "https://github.com/kkollsga/sheetio"
license = "MIT"
keywords = ["excel", "data-extraction", "json", "spreadsheet", "pandas"]
categories = ["data-processing", "parsing", "excel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_sheetio"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.102"
calamine = "0.35.0"
chrono = "0.4.44"
futures = "0.3.32"
indexmap = "2.14.0"
pyo3 = "0.28.3"
serde_json = { version = "1.0.150", features = ["preserve_order"] }
tokio = {version = "1.52.3", features = ["full"] }
